### ISSUE TITLE
Exception loading model errors

### ISSUE THREAD

**Issue by ghost** [The-Fireplace/Adobe-Blocks#2]
Found in the log:

```
[08:52:25] [Client thread/ERROR] [FML]: Exception loading model for variant adobeblocks:adobe_slab#half=top,variant=true
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model adobeblocks:adobe_slab#half=top,variant=true with loader VariantLoader.INSTANCE, skipping
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
    at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:241) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:145) ~[byo.class:?]
    at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:229) ~[ModelLoader.class:?]
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:146) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132) [bxi.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113) [bxi.class:?]
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755) [bcx.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:338) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
    at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) ~[bpe.class:?]
    at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) ~[ModelLoader$VariantLoader.class:?]
    at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
    ... 18 more
```

I think it's not normal but the mod seems to work fine so far...
Is it possible that other mods are causing this?

Minecraft Version: 1.10.2
Forge Version: 1.10.2-12.18.1.2076-universal
Adobe Blocks Version: 6.0.3.23

**Comment by The-Fireplace** [comment]
Everything works fine in-game.

**Comment by ghost** [comment]
That's right, but think of it this way... Bloating a log with error messages while the program just works fine needlessly extends the debugging process. It's a matter of good practice.

**Comment by The-Fireplace** [comment]
I'm not the one putting the error messages there. Sure, I guess I could look in to it and see if there is any efficient way to prevent them, but no promises.
